-- ============================================
-- CHINOOK SALES DATA ANALYSIS PROJECT
-- ============================================

-- =========================================================
-- DATA VALIDATION & CLEANING PROCESS
-- =========================================================

-- ---------------------------------------------------------
-- 1. Duplicate Validation on Primary Key Columns
-- Purpose: To ensure data integrity by checking whether 
-- any primary key values are duplicated in major tables.
-- ---------------------------------------------------------

-- Checking duplicate Customer IDs
SELECT customer_id, COUNT(*)
FROM customer
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- Checking duplicate Invoice IDs
SELECT invoice_id, COUNT(*)
FROM invoice
GROUP BY invoice_id
HAVING COUNT(*) > 1;

-- Checking duplicate Track IDs
SELECT track_id, COUNT(*)
FROM track
GROUP BY track_id
HAVING COUNT(*) > 1;

-- Checking duplicate Album IDs
SELECT album_id, COUNT(*)
FROM album
GROUP BY album_id
HAVING COUNT(*) > 1;

-- Checking duplicate Email IDs (Business-level duplicate validation)
SELECT email, COUNT(*)
FROM customer
GROUP BY email
HAVING COUNT(*) > 1;


-- ---------------------------------------------------------
-- 2. Missing Value Validation in Critical Columns
-- Purpose: To verify that key analytical columns 
-- do not contain NULL values.
-- ---------------------------------------------------------

-- Checking NULL values in customer email
SELECT COUNT(*) 
FROM customer
WHERE email IS NULL;

-- Checking NULL values in invoice total amount
SELECT COUNT(*) 
FROM invoice
WHERE total IS NULL;


-- ---------------------------------------------------------
-- 3. Missing Value Validation in Non-Critical Columns
-- Purpose: To identify NULL values in descriptive fields 
-- that do not affect revenue analysis.
-- ---------------------------------------------------------

-- Checking NULL values in company column
SELECT COUNT(*) AS Null_Company
FROM customer
WHERE company IS NULL;

-- Checking NULL values in fax column
SELECT COUNT(*) AS Null_Fax
FROM customer
WHERE fax IS NULL;


-- ---------------------------------------------------------
-- 4. Handling Missing Values in Non-Critical Fields
-- Purpose: Replace NULL or blank company values with 
-- 'Not Provided' to maintain reporting consistency.
-- ---------------------------------------------------------

UPDATE chinook.customer
SET company = 'Not Provided'
WHERE company IS NULL
   OR company = '';

-- Re-validation to confirm NULL removal
USE chinook;

SELECT COUNT(*)
FROM customer
WHERE company IS NULL;


-- ==================================================
-- SECTION 1: BUSINESS OVERVIEW
-- ==================================================

-- Query 1: Calculate Total Revenue Generated
SELECT ROUND(SUM(total),2) AS Total_Revenue
FROM invoice;

-- Query 2: Count Total Customers
SELECT COUNT(*) AS Total_Customers
FROM customer;

-- Query 3: Count Total Invoices Generated
SELECT COUNT(*) AS Total_Invoices
FROM invoice;

-- Query 4: Calculate Average Revenue Per Customer
SELECT ROUND(SUM(total)/COUNT(DISTINCT customer_id),2) 
AS Avg_Revenue_Per_Customer
FROM invoice;


-- ==================================================
-- SECTION 2: GEOGRAPHIC ANALYSIS
-- ==================================================

-- Query 5: Revenue Generated by Each Country
SELECT billing_country,
ROUND(SUM(total),2) AS Total_Sales
FROM invoice
GROUP BY billing_country
ORDER BY Total_Sales DESC;

-- Query 6: Top 5 Cities by Revenue
SELECT billing_city,
ROUND(SUM(total),2) AS Total_Revenue
FROM invoice
GROUP BY billing_city
ORDER BY Total_Revenue DESC
LIMIT 5;


-- ==================================================
-- SECTION 3: CUSTOMER ANALYSIS
-- ==================================================

-- Query 7: Top 5 Customers by Total Spending
SELECT c.customer_id,
CONCAT(c.first_name,' ',c.last_name) AS Customer_Name,
ROUND(SUM(i.total),2) AS Total_Spent
FROM customer c
JOIN invoice i 
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, Customer_Name
ORDER BY Total_Spent DESC
LIMIT 5;

-- Query 8: Number of Customers by Country
SELECT country,
COUNT(*) AS Total_Customers
FROM customer
GROUP BY country
ORDER BY Total_Customers DESC;


-- ==================================================
-- SECTION 4: PRODUCT & GENRE ANALYSIS
-- ==================================================

-- Query 9: Top 5 Selling Genres
SELECT g.name AS Genre,
SUM(il.quantity) AS Total_Sold
FROM invoice_line il
JOIN track t ON il.track_id = t.track_id
JOIN genre g ON t.genre_id = g.genre_id
GROUP BY g.name
ORDER BY Total_Sold DESC
LIMIT 5;

-- Query 10: Top 5 Selling Artists
SELECT ar.name AS Artist,
SUM(il.quantity) AS Total_Sold
FROM invoice_line il
JOIN track t ON il.track_id = t.track_id
JOIN album al ON t.album_id = al.album_id
JOIN artist ar ON al.artist_id = ar.artist_id
GROUP BY ar.name
ORDER BY Total_Sold DESC
LIMIT 5;

-- Query 11: Most Expensive Tracks
SELECT name,
unit_price
FROM track
ORDER BY unit_price DESC
LIMIT 5;


-- ==================================================
-- SECTION 5: SALES TREND ANALYSIS
-- ==================================================

-- Query 12: Monthly Revenue Trend
SELECT 
DATE_FORMAT(invoice_date,'%Y-%m') AS Month,
ROUND(SUM(total),2) AS Monthly_Revenue
FROM invoice
GROUP BY Month
ORDER BY Month;


-- ==================================================
-- SECTION 6: EMPLOYEE PERFORMANCE ANALYSIS
-- ==================================================

-- Query 13: Revenue Handled by Each Support Representative
SELECT 
e.first_name,
e.last_name,
ROUND(SUM(i.total),2) AS Revenue_Handled
FROM employee e
JOIN customer c ON e.employee_id = c.support_rep_id
JOIN invoice i ON c.customer_id = i.customer_id
GROUP BY e.employee_id
ORDER BY Revenue_Handled DESC;
